--------------------------------------------------------
-- Archivo creado  - domingo-febrero-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HS_STOCK_PRODUCTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HULK_STORE"."HS_STOCK_PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HS_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HULK_STORE"."HS_PRODUCTO" 
   (	"CODIGO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"TIPO_PRODUCTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HS_STOCK_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HULK_STORE"."HS_STOCK_PRODUCTO" 
   (	"CODIGO" NUMBER, 
	"CODIGO_PRODUCTO" NUMBER, 
	"STOCK" NUMBER, 
	"FECHA_MOVIMIENTO" DATE, 
	"TIPO_MOVIMIENTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HS_TIPO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HULK_STORE"."HS_TIPO_PRODUCTO" 
   (	"CODIGO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"FECHA_REGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HULK_STORE.HS_PRODUCTO
SET DEFINE OFF;
Insert into HULK_STORE.HS_PRODUCTO (CODIGO,NOMBRE,TIPO_PRODUCTO) values ('1','CAMISETA MANGA LARGA','1');
Insert into HULK_STORE.HS_PRODUCTO (CODIGO,NOMBRE,TIPO_PRODUCTO) values ('2','CAMISETA MANGA CORTA','1');
Insert into HULK_STORE.HS_PRODUCTO (CODIGO,NOMBRE,TIPO_PRODUCTO) values ('3','JUEGO DE VASOS MARVEL','2');
Insert into HULK_STORE.HS_PRODUCTO (CODIGO,NOMBRE,TIPO_PRODUCTO) values ('4','JUEGO DE VASOS DC COMICS','2');
REM INSERTING into HULK_STORE.HS_STOCK_PRODUCTO
SET DEFINE OFF;
Insert into HULK_STORE.HS_STOCK_PRODUCTO (CODIGO,CODIGO_PRODUCTO,STOCK,FECHA_MOVIMIENTO,TIPO_MOVIMIENTO) values ('9','1','6',to_date('14/02/2021','DD/MM/RRRR'),null);
REM INSERTING into HULK_STORE.HS_TIPO_PRODUCTO
SET DEFINE OFF;
Insert into HULK_STORE.HS_TIPO_PRODUCTO (CODIGO,NOMBRE,FECHA_REGISTRO) values ('1','PRENDAS DE VESTIR',to_date('14/02/2021','DD/MM/RRRR'));
Insert into HULK_STORE.HS_TIPO_PRODUCTO (CODIGO,NOMBRE,FECHA_REGISTRO) values ('2','UTENZILLOS',to_date('14/02/2021','DD/MM/RRRR'));
Insert into HULK_STORE.HS_TIPO_PRODUCTO (CODIGO,NOMBRE,FECHA_REGISTRO) values ('3','COMICS',to_date('14/02/2021','DD/MM/RRRR'));
Insert into HULK_STORE.HS_TIPO_PRODUCTO (CODIGO,NOMBRE,FECHA_REGISTRO) values ('5','ACCESORIOS Y OTROS',to_date('14/02/2021','DD/MM/RRRR'));
Insert into HULK_STORE.HS_TIPO_PRODUCTO (CODIGO,NOMBRE,FECHA_REGISTRO) values ('4','JUGUETERIA',to_date('14/02/2021','DD/MM/RRRR'));
--------------------------------------------------------
--  DDL for Index HS_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HULK_STORE"."HS_PRODUCTO_PK" ON "HULK_STORE"."HS_PRODUCTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HS_STOCK_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HULK_STORE"."HS_STOCK_PRODUCTO_PK" ON "HULK_STORE"."HS_STOCK_PRODUCTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HS_TIPO_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HULK_STORE"."HS_TIPO_PRODUCTO_PK" ON "HULK_STORE"."HS_TIPO_PRODUCTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HS_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HULK_STORE"."HS_PRODUCTO" ADD CONSTRAINT "HS_PRODUCTO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HULK_STORE"."HS_PRODUCTO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HS_STOCK_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HULK_STORE"."HS_STOCK_PRODUCTO" ADD CONSTRAINT "HS_STOCK_PRODUCTO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HULK_STORE"."HS_STOCK_PRODUCTO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HS_TIPO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HULK_STORE"."HS_TIPO_PRODUCTO" ADD CONSTRAINT "HS_TIPO_PRODUCTO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HULK_STORE"."HS_TIPO_PRODUCTO" MODIFY ("CODIGO" NOT NULL ENABLE);
